// ── Tiny safe markdown renderer ─────────────────────────────────────────────
//
// The audit report is markdown generated by Claude. We render it as
// HTML inside the admin page. Since the source is OUR system (not
// user input), we don't need a full markdown parser with XSS hardening
// — but we do want a small, dependency-free renderer that handles the
// constructs the audit prompt actually emits:
//   - # / ## / ### headings
//   - **bold** / *italic*
//   - `inline code`
//   - bulleted lists with -
//   - numbered lists with 1.
//   - paragraphs separated by blank lines
//   - [text](url) links — relative paths preserved

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function inline(s: string): string {
  let out = escapeHtml(s)
  // links — [text](href). Done before bold/italic so they don't
  // accidentally break.
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, t, h) => {
    const href = h.startsWith('/') || h.startsWith('http') ? h : '#'
    return `<a href="${href}" target="_blank" rel="noopener noreferrer">${t}</a>`
  })
  // bold + italic — naive but safe for our generated content.
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  out = out.replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
  // inline code
  out = out.replace(/`([^`]+)`/g, '<code>$1</code>')
  return out
}

export function renderMarkdownToHtml(md: string): string {
  const lines = md.split('\n')
  const blocks: string[] = []
  let listKind: 'ul' | 'ol' | null = null
  let listItems: string[] = []
  let paragraph: string[] = []

  function flushParagraph() {
    if (paragraph.length) {
      blocks.push(`<p>${inline(paragraph.join(' '))}</p>`)
      paragraph = []
    }
  }
  function flushList() {
    if (listKind && listItems.length) {
      const items = listItems.map(it => `<li>${inline(it)}</li>`).join('')
      blocks.push(`<${listKind}>${items}</${listKind}>`)
      listItems = []
    }
    listKind = null
  }

  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '')
    if (!line.trim()) {
      flushParagraph()
      flushList()
      continue
    }
    // Headings
    const h = line.match(/^(#{1,6})\s+(.*)$/)
    if (h) {
      flushParagraph(); flushList()
      const level = Math.min(6, h[1].length)
      blocks.push(`<h${level}>${inline(h[2])}</h${level}>`)
      continue
    }
    // Bulleted list
    const ul = line.match(/^[-*]\s+(.*)$/)
    if (ul) {
      flushParagraph()
      if (listKind !== 'ul') flushList()
      listKind = 'ul'; listItems.push(ul[1])
      continue
    }
    // Numbered list
    const ol = line.match(/^\d+\.\s+(.*)$/)
    if (ol) {
      flushParagraph()
      if (listKind !== 'ol') flushList()
      listKind = 'ol'; listItems.push(ol[1])
      continue
    }
    // Paragraph continuation
    flushList()
    paragraph.push(line)
  }
  flushParagraph()
  flushList()

  return blocks.join('\n')
}
