import type { Metadata } from 'next'
import { Suspense } from 'react'
import { Geist, Geist_Mono, Allura, Fraunces, Inter, Montserrat, Playfair_Display } from 'next/font/google'
import Script from 'next/script'
import { ViewTracker } from '@/components/ViewTracker'
import { loadBrandContext } from '@/lib/brand-context'
import { chromeForBrand } from '@/lib/brands'
import { organizationJsonLd, websiteJsonLd, jsonLdScript } from '@/lib/seo/jsonld'
import './globals.css'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })
// Allura — magazine-style cursive used for column wordmarks (e.g. Grands
// Are the Greatest). Loaded once site-wide via CSS var so any column-brand
// wordmark can reference --font-allura without re-importing.
const allura    = Allura({ variable: '--font-allura', weight: '400', subsets: ['latin'], display: 'swap' })
// Fraunces — editorial serif used for headings on the games surface and
// in select feature/long-form contexts. Loaded once site-wide via CSS
// var so any component can reference --font-fraunces without re-importing.
const fraunces  = Fraunces({ variable: '--font-fraunces', weight: ['600', '700', '900'], subsets: ['latin'], display: 'swap' })

// 50+ template family fonts. Loaded site-wide as CSS variables and only
// applied inside the .fifty-plus-page scope (see globals.css). Loading
// site-wide costs ~3 small WOFF2 fetches; in exchange we get a single
// root layout that serves both brand families without a route split.
const inter      = Inter({            variable: '--font-inter',     subsets: ['latin'], display: 'swap' })
const montserrat = Montserrat({       variable: '--font-montserrat', weight: ['600', '700', '800', '900'], subsets: ['latin'], display: 'swap' })
const playfair   = Playfair_Display({ variable: '--font-playfair',  weight: ['400', '600', '700'],        subsets: ['latin'], display: 'swap' })

/** Brand-aware site metadata. The default title + description come from
 *  the resolved brand (display name + tagline + audience summary), so a
 *  reader landing on the BOOM domain sees BOOM metadata in their browser
 *  tab + share previews, not RRP boilerplate. The favicon stays the legacy
 *  RRP asset until brand-specific favicons are configured.
 *
 *  metadataBase + openGraph.images + twitter card are now defined at the
 *  ROOT so every page in the app gets a sensible default share preview
 *  without re-stating it per page. Pages that want a more specific
 *  image (article hero, event flyer) override via their own
 *  generateMetadata that calls buildPageMetadata({ image: ... }). The
 *  default OG image is generated by the colocated /opengraph-image.tsx
 *  route — see that file for the brand wordmark rendering. */
export async function generateMetadata(): Promise<Metadata> {
  const ctx = await loadBrandContext()
  const chrome = chromeForBrand(ctx.brand)
  return {
    metadataBase: new URL(ctx.publicOrigin),
    title:       `${ctx.market.displayName} — Local Stories & Events`,
    description: chrome.tagline,
    icons: {
      icon: '/images/advertise/rrp-logo.png',
      apple: '/images/advertise/rrp-logo.png',
    },
    openGraph: {
      siteName:    ctx.market.displayName,
      type:        'website',
      url:         ctx.publicOrigin,
      title:       ctx.market.displayName,
      description: chrome.tagline,
      locale:      'en_US',
      // No `images` here — Next.js falls through to /opengraph-image.tsx
      // automatically. When a page wants a more specific image it
      // overrides via per-route generateMetadata.
    },
    twitter: {
      card:        'summary_large_image',
      title:       ctx.market.displayName,
      description: chrome.tagline,
    },
    robots: {
      index:    true,
      follow:   true,
      googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
    },
  }
}

// Plausible: set NEXT_PUBLIC_PLAUSIBLE_DOMAIN (e.g. "riverregionparents.com")
// in production to enable. Local + preview builds without it just render
// without the script — zero tracking, zero pollution of your stats.
const plausibleDomain = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Site-wide structured data. Organization tells search engines who
  // we are (name, logo, social profiles); WebSite registers our
  // search action so Google can show a sitelinks search box. Both
  // are emitted ONCE per page from the root layout so we don't
  // duplicate them across route segments.
  const ctx = await loadBrandContext()
  const orgLd = organizationJsonLd({
    name:    ctx.market.displayName,
    url:     ctx.publicOrigin,
    logoUrl: `${ctx.publicOrigin}/images/advertise/rrp-logo.png`,
    socialUrls: [
      'https://www.facebook.com/riverregionparents',
      'https://www.instagram.com/riverregionparents',
    ],
  })
  const siteLd = websiteJsonLd({
    name:       ctx.market.displayName,
    url:        ctx.publicOrigin,
    searchPath: '/articles?q={search_term_string}',
  })

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${allura.variable} ${fraunces.variable} ${inter.variable} ${montserrat.variable} ${playfair.variable} h-full antialiased`}
    >
      <head>
        {plausibleDomain && (
          <Script
            defer
            strategy="afterInteractive"
            data-domain={plausibleDomain}
            src="https://plausible.io/js/script.tagged-events.outbound-links.js"
          />
        )}
        {/* JSON-LD structured data — Organization + WebSite. Inlined
            via dangerouslySetInnerHTML so it ships in the initial HTML
            and search-engine crawlers see it without executing JS. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(orgLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(siteLd) }}
        />
      </head>
      <body className="h-full">
        {/* First-party pageview tracking — feeds the auto-trending bar +
            analytics surface. Wrapped in Suspense because it uses
            useSearchParams() (to capture UTMs at the URL) which would
            otherwise opt the whole tree out of static rendering. */}
        <Suspense fallback={null}>
          <ViewTracker />
        </Suspense>
        {children}
      </body>
    </html>
  )
}
