import type { Metadata } from 'next'
import { Suspense } from 'react'
import { Geist, Geist_Mono, Allura, Fraunces, Inter, Montserrat, Playfair_Display } from 'next/font/google'
import Script from 'next/script'
import { ViewTracker } from '@/components/ViewTracker'
import { loadBrandContext } from '@/lib/brand-context'
import { chromeForBrand } from '@/lib/brands'
import { newsMediaOrganizationJsonLd, websiteJsonLd, jsonLdScript } from '@/lib/seo/jsonld'
import { getBrandSeoConfig } from '@/lib/seo/brand-seo'
import './globals.css'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })
// Allura — magazine-style cursive used for column wordmarks (e.g. Grands
// Are the Greatest). Loaded once site-wide via CSS var so any column-brand
// wordmark can reference --font-allura without re-importing.
const allura    = Allura({ variable: '--font-allura', weight: '400', subsets: ['latin'], display: 'swap' })
// Fraunces — editorial serif used for headings on the games surface and
// in select feature/long-form contexts. Loaded once site-wide via CSS
// var so any component can reference --font-fraunces without re-importing.
const fraunces  = Fraunces({ variable: '--font-fraunces', weight: ['600', '700', '900'], subsets: ['latin'], display: 'swap' })

// 50+ template family fonts. Loaded site-wide as CSS variables and only
// applied inside the .fifty-plus-page scope (see globals.css). Loading
// site-wide costs ~3 small WOFF2 fetches; in exchange we get a single
// root layout that serves both brand families without a route split.
const inter      = Inter({            variable: '--font-inter',     subsets: ['latin'], display: 'swap' })
const montserrat = Montserrat({       variable: '--font-montserrat', weight: ['600', '700', '800', '900'], subsets: ['latin'], display: 'swap' })
const playfair   = Playfair_Display({ variable: '--font-playfair',  weight: ['400', '600', '700'],        subsets: ['latin'], display: 'swap' })

/** Brand-aware site metadata. The default title + description come from
 *  the resolved brand (display name + tagline + audience summary), so a
 *  reader landing on the BOOM domain sees BOOM metadata in their browser
 *  tab + share previews, not RRP boilerplate. The favicon stays the legacy
 *  RRP asset until brand-specific favicons are configured.
 *
 *  metadataBase + openGraph.images + twitter card are now defined at the
 *  ROOT so every page in the app gets a sensible default share preview
 *  without re-stating it per page. Pages that want a more specific
 *  image (article hero, event flyer) override via their own
 *  generateMetadata that calls buildPageMetadata({ image: ... }). The
 *  default OG image is generated by the colocated /opengraph-image.tsx
 *  route — see that file for the brand wordmark rendering. */
export async function generateMetadata(): Promise<Metadata> {
  const ctx = await loadBrandContext()
  const chrome = chromeForBrand(ctx.brand)
  return {
    metadataBase: new URL(ctx.publicOrigin),
    title:       `${ctx.market.displayName} — Local Stories & Events`,
    description: chrome.tagline,
    icons: {
      icon: '/images/advertise/rrp-logo.png',
      apple: '/images/advertise/rrp-logo.png',
    },
    openGraph: {
      siteName:    ctx.market.displayName,
      type:        'website',
      url:         ctx.publicOrigin,
      title:       ctx.market.displayName,
      description: chrome.tagline,
      locale:      'en_US',
      // No `images` here — Next.js falls through to /opengraph-image.tsx
      // automatically. When a page wants a more specific image it
      // overrides via per-route generateMetadata.
    },
    twitter: {
      card:        'summary_large_image',
      title:       ctx.market.displayName,
      description: chrome.tagline,
    },
    robots: {
      index:    true,
      follow:   true,
      googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
    },
    // Verification meta tags — pulled from env so they don't ship
    // hardcoded in source. Set GOOGLE_SITE_VERIFICATION (Search
    // Console) + BING_SITE_VERIFICATION (Bing Webmaster Tools) +
    // YANDEX_SITE_VERIFICATION (if relevant) in env when you have
    // the property tokens. Each tag is omitted when its env var
    // is missing so unverified surfaces don't ship empty tags.
    verification: {
      google: process.env.GOOGLE_SITE_VERIFICATION,
      yandex: process.env.YANDEX_SITE_VERIFICATION,
      other: {
        ...(process.env.BING_SITE_VERIFICATION && { 'msvalidate.01': process.env.BING_SITE_VERIFICATION }),
        ...(process.env.PINTEREST_SITE_VERIFICATION && { 'p:domain_verify': process.env.PINTEREST_SITE_VERIFICATION }),
        ...(process.env.FACEBOOK_DOMAIN_VERIFICATION && { 'facebook-domain-verification': process.env.FACEBOOK_DOMAIN_VERIFICATION }),
      },
    },
  }
}

// Plausible: set NEXT_PUBLIC_PLAUSIBLE_DOMAIN (e.g. "riverregionparents.com")
// in production to enable. Local + preview builds without it just render
// without the script — zero tracking, zero pollution of your stats.
const plausibleDomain = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Site-wide structured data. NewsMediaOrganization tells Google we
  // are a legitimate local-news publisher (vs a generic Organization);
  // WebSite registers a SearchAction so Google can show a sitelinks
  // search box. Both inherit brand identity from the resolved request
  // so RRP, BOOM, AOP, MBP all emit their own publisher schema with
  // their own social profiles, founding date, knowsAbout list, and
  // area served. Adding a new brand = MARKETS row + (optional)
  // BRAND_OVERRIDES entry in brand-seo.ts and the schema flows.
  const ctx     = await loadBrandContext()
  const seoCfg  = getBrandSeoConfig(ctx.market, ctx.publicOrigin)
  const orgLd   = newsMediaOrganizationJsonLd({
    name:                 seoCfg.organizationName,
    legalName:            seoCfg.legalName,
    url:                  seoCfg.url,
    logoUrl:              seoCfg.logoUrl,
    slogan:               seoCfg.slogan,
    foundingYear:         seoCfg.foundingYear,
    socialUrls:           seoCfg.socialUrls,
    knowsAbout:           seoCfg.knowsAbout,
    audience:             seoCfg.audience,
    areaServedLabel:      seoCfg.areaServedLabel,
    addressLocality:      seoCfg.addressLocality,
    addressRegion:        seoCfg.addressRegion,
    addressCountry:       seoCfg.addressCountry,
    contactEmail:         seoCfg.contactEmail,
    editorialPolicyUrl:   seoCfg.editorialPolicyUrl,
    ethicsPolicyUrl:      seoCfg.ethicsPolicyUrl,
    correctionsPolicyUrl: seoCfg.correctionsPolicyUrl,
    aboutUrl:             seoCfg.aboutUrl,
  })
  const siteLd  = websiteJsonLd({
    name:       seoCfg.organizationName,
    url:        seoCfg.url,
    searchPath: '/articles?q={search_term_string}',
  })

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${allura.variable} ${fraunces.variable} ${inter.variable} ${montserrat.variable} ${playfair.variable} h-full antialiased`}
    >
      <head>
        {plausibleDomain && (
          <Script
            defer
            strategy="afterInteractive"
            data-domain={plausibleDomain}
            src="https://plausible.io/js/script.tagged-events.outbound-links.js"
          />
        )}
        {/* JSON-LD structured data — NewsMediaOrganization + WebSite.
            Inlined via dangerouslySetInnerHTML so it ships in the
            initial HTML and crawlers see it without executing JS. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(orgLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(siteLd) }}
        />
        {/* Auto-discovery links — feed readers + crawlers parse these
            from the head. RSS feed, news sitemap, and PWA manifest
            all advertised so every well-behaved client picks them up
            without a manual subscribe step. */}
        <link rel="alternate" type="application/rss+xml" title={`${ctx.market.displayName} — Latest`} href="/feed.xml" />
        <link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <meta name="theme-color" content={seoCfg.brandColor} />
      </head>
      <body className="h-full">
        {/* First-party pageview tracking — feeds the auto-trending bar +
            analytics surface. Wrapped in Suspense because it uses
            useSearchParams() (to capture UTMs at the URL) which would
            otherwise opt the whole tree out of static rendering. */}
        <Suspense fallback={null}>
          <ViewTracker />
        </Suspense>
        {children}
      </body>
    </html>
  )
}
