-- ── Migration 196 — Social post copy (separate from SEO) ────────────
--
-- SEO copy ≠ Social post copy. They have different jobs:
--   - SEO copy (seo_title, seo_description): rank in Google + render
--     the Open Graph link-preview card. Read by algorithms and the
--     small text in a link card. Optimize for keywords + intent + flow.
--   - Social post copy (social_hook, social_fb_caption,
--     social_ig_caption): make a parent stop scrolling and click.
--     Friend-voice, conversational, varied tone.
--
-- This migration adds the dedicated social fields. Migration 187's
-- seo_title / seo_description / seo_focus_keyword stay as-is, but
-- the bulk seeder will re-seed them with a PURE-SEO prompt (no
-- social blending), and the inline panel will split into separate
-- Social Sharing + SEO surfaces.

ALTER TABLE guide_articles
  -- The one-line hook — the "Why click?" lead question/statement.
  -- Used as the FB caption opener and the IG first line.
  ADD COLUMN IF NOT EXISTS social_hook       TEXT,

  -- Full per-platform caption overrides. When NULL, the queue dispatcher
  -- generates from the article body + brand voice + tone setting.
  ADD COLUMN IF NOT EXISTS social_fb_caption TEXT,
  ADD COLUMN IF NOT EXISTS social_ig_caption TEXT,

  -- Tone selector — drives the caption generator. Editor can pin a
  -- specific tone for an article; otherwise the AI rotates.
  --   supportive   — coach / friend / partner (default mix)
  --   celebratory  — "look at this win" energy
  --   funny        — playful, light, self-aware
  --   inspiring    — hopeful, uplifting, possibility-focused
  --   practical    — "here's the answer" + direct value
  --   tender       — soft, emotional, family-warmth moments
  ADD COLUMN IF NOT EXISTS social_voice_tone TEXT
    CHECK (social_voice_tone IN ('supportive','celebratory','funny','inspiring','practical','tender') OR social_voice_tone IS NULL),

  -- Provenance — when the bulk social seeder filled these in.
  ADD COLUMN IF NOT EXISTS social_ai_seeded_at TIMESTAMPTZ;

COMMENT ON COLUMN guide_articles.social_hook IS
  'One-line hook — the lead question/statement that gets a parent to stop scrolling. Friend-voice; never manipulative.';
COMMENT ON COLUMN guide_articles.social_fb_caption IS
  'Editor-tuned Facebook post caption. When NULL, generated by AI at queue dispatch time.';
COMMENT ON COLUMN guide_articles.social_ig_caption IS
  'Editor-tuned Instagram post caption (no link — "link in bio" pattern). When NULL, generated by AI.';
COMMENT ON COLUMN guide_articles.social_voice_tone IS
  'Tone pin for AI generation. NULL = AI rotates tones across articles to keep the feed varied.';
COMMENT ON COLUMN guide_articles.social_ai_seeded_at IS
  'Timestamp when the bulk social seeder filled in social_hook / captions. NULL = editor-written or never seeded.';

CREATE INDEX IF NOT EXISTS idx_guide_articles_social_ai_seeded
  ON guide_articles (social_ai_seeded_at)
  WHERE social_ai_seeded_at IS NOT NULL;
